Source/PluginParam.cpp
Fixes not being able to dial in certain parameter values.
Also fixes way hosts (e.g. Reaper) Parameter modulation by LFO works with dexed.
bug 
-Middle C Transpose not displaying 'C5'. 
bug
-Cannot dial in certain parameter values. Float rounding error, value rounded down where it becomes int.
e.g. 	Parameters that go from 0-99 skip values: 53,59
Middle C Transpose skips value D#3
bug
- Host Reaper Parameter Modulation by LFO not modulating correctly with dexed. 
e.g. LFO triangle shape stays on max and min value too long when modulating a dexed parameter.
Lowering 'steps' values by one corrects LFO duration at max value. Rounding to nearest int corrects LFO duration on min value. Also the hosts UI, better displays the max value to be at the far right of the slider and doesn't leave extra …
=> Fix for parameter values, and host parameter modulation by LFO

Source/msfa/dx7note.cc
Adjustment to break point level scaling to match Yamaha DX7.
Comparison image shows C1 to C4,  break point C3, -Lin curve, Depth 99
=> Adjustment to break point level scaling

Source/PluginEditor.cpp
Fix bug with 'External File' button giving an error with a good sysex file.
Fix bug with  '...create a new copy of the syx cartridge'  not working if user had loaded a cartridge.
=> some fixes for the STORE dialog

Source/EngineMkI.cpp, Source/EngineOpl.cpp
vs2013+ support C99 **round** and **log2** functions, so let's get rid of warning
=> use native log2 and round in vs2013+

Source/msfa/env.cc
minor cleanup.
off-topic, you may have forgotten to check in the OSX Icon.icns file.
=> ensure staticrate maximum

Source/CartManager.cpp, Source/GlobalEditor.cpp, Source/OperatorEditor.cpp, Source/PluginParam.cpp, Source/ProgramListBox.cpp
Resolves a conflict with fine tune modifier also bringing up the Popup menu.  (Ctrl with left mouse button)
- Using Shift to fine tune sliders, (Ctrl click already reserved on Mac to emulate right click.)
- Using typical method to show Popup menus. On Windows/Linux right click. On Mac Ctrl click, or right click.
#140
=> edited Fine tune modifier key,  and Popup menu modifier.

JuceLibraryCode/AppConfig.h
#132
works around the null pointer error.
=> Workaround for crash initializing the ALSA client

Source/DXLookNFeel.h, Source/EngineMkI.cpp, Source/GlobalEditor.cpp, Source/PluginData.cpp, Source/PluginData.h, Source/PluginEditor.cpp, Source/PluginProcessor.cpp, Source/msfa/dx7note.cc, Source/msfa/env.cc
Found via `codespell -q 3 -S ./JuceLibraryCode`
=> Fix misc. typos

Source/ParamDialog.cpp
Also rename After Touch to Aftertouch. :)
Should fix #188 I think. Does this adjustment need to be done anywhere else?
=> Swap positions of Breath and Foot labels on PARM

Source/GlobalEditor.cpp, Source/PluginEditor.cpp, Source/PluginEditor.h, Source/PluginParam.cpp
This patch implements basic UI scaling in a simple way: if the current display DPI is above a threshold, everything is scaled by 1.5 including the size of the window. This works great on my Retina Macbook and makes everything much more usable.
In the process of doing this I noticed some UI slow down coming from excessive repainting as parameters are changing. The end result with my changes is more responsive feeling knobs and sliders. I'm pretty sure that every part of the UI is still repainting as expected but that could use a quick review to make sure I didn't miss anything.
Cheers!
=> Basic UI scaling for HiDPI screens and some rendering optimization

scripts/get-juce.sh
The linux nightly build is broken on Ubuntu due to a JUCE Makefile error; the correct std version is not being set. 
Error: `unordered_map’ in namespace ‘std’ does not name a template type` which indicates the `std=c++17` compiler flag is not being correctly set. Manually bumping the version number from 6.0.0->6.0.1 fixes this.
=> Update get-juce.sh to use the latest JUCE version

scripts/release-notes.sh
Hi! I'm super glad you got the azure pipelines running. Some folks over on KVR today discovered the changes we've collaborated on and I saw that you got nightlies up and running. I've adjusted our website to push people to your nightlies and so on. Very exciting!
One thing I noticed was the release notes still say surge and so on. This PR is just a tiny wording change which will update the text in the nightlies at asb2m10/dexed.
Oh and folks were very excited about a tunable dexed. Fun stuff!
=> Clean up release note language

README.md
Added the solution to  missing header files compilation errors from one of the reported issues.
=> Linux - missing header files compilation errors

Source/EngineMkI.cpp
Pushing the feedback value up to 7 in algorithm 32 results in digital noise, see issue asb2m10#146.
That's not how the original DX7 behaves.
This patch tries to fix this issue by scaling the feedback value for algorithm 32. It sounds
much closer to the (at least my) DX7 Mk I and doesn't produce the digital noise any more.
In direct comparison, at feedback value 7 it sounds a bit brighter than my original DX7.
I tried different scalings (e.g. feedback_shift+3) which sounded a bit too muffled.
So overall (feedback_shift+2) sounds closest to my DX7.
This might need further investigaion but for now I think that this scaling is much better than
the digital noise currently produced.
=> Adjust feedback for algorithm 32 in Mk I engine

CMake/CPM.cmake, CMakeLists.txt, README_cmake.md, Resources/CMakeLists.txt, Source/CMakeLists.txt, libs/CMakeLists.txt
This adds support for the cmake build system. I don't regard it as complete ny any means. It is very basic and has only been tested on Debian. It doesn't conflict, though, with the projucer based build system. Not a single existing file had to be changed. So this might serve as a first step towards a proper transistion to cmake.
Please, see README_cmake.md for the details.
=> Initial cmake support

.gitignore, Source/CartManager.cpp, Source/PluginProcessor.cpp
`dexed/Source/PluginProcessor.cpp:776:11: error: invalid use of template-name ‘juce::Rectangle’`
see also https://github.com/asb2m10/dexed/issues/324#issuecomment-1086916677
+ stop some leakage in CartManager
=> Fix a Linux build error

CMakeLists.txt, README_cmake.md, Source/CMakeLists.txt, Source/PluginFx.cpp, Source/PluginProcessor.cpp, Source/msfa/tuning.cc
- remove `juce_recommended_warning_flags`
This otherwise builds with `-Wall -Wextra` which shows a lot of less- or unimportant
warnings with the important ones lost inbetween, plus you can not supress warnings.
- move recommended lto and config flags to public as per juce recomendation
- fix a few warnings
- update tuningui submodule
In total this brings the 2k+ displayed warnings down to managable 28
which are a few deprecated-declarations and two unused values.
- add configurable option to add or supress warnings to CMakeLists.txt
turned on as an example for linux, which in this example supresses the remaining warnings
while newly introduced warnings will error.
=> More CMake changes and less warnings

Source/PluginProcessor.cpp, Source/PluginProcessor.h
Without configuration the plugin would expose a multitude of input and output channels, at least when used
in Carla. The projucer's pluginChannelConfigs option cannot be carried over to the cmake build system
so, following [1], channel configuration is done using the buses API .
[1] https://github.com/juce-framework/JUCE/blob/master/docs/CMake%20API.md
=> Use buses API for channel configuration

CMakeLists.txt
Since JUCE and CLAP were included in CMake *before* the MSVC
Runtime was picked, the CLAP CMake picked the system default which
in some build configurations would lead to a conflict at link time.
Fix this by simply moving the include of JUCE and JUCE CLap Extensions
to after the set up of architecture, runtime, etc...
=> Fix a Windows CLAP linker error

CMakeLists.txt, Source/CMakeLists.txt
- adds build option `-DDEXED_SKIP_VST3=1`
and `-DDEXED_NO_ALSA=1`
to enable the FreeBSD port
- don't turn on `-Werror` just yet
Closes #322
Closes #340
Closes #343
=> Make VST3 and ALSA skippable in cmake

Source/ParamDialog.cpp
User @trancybabe opened the issue [#420](https://github.com/asb2m10/dexed/issues/420), indicating that the predefined size selections of Dexed's GUI are too small for high resolution displays such as 6K retina monitors.
In response to this issue, this commit introduces new size options: 200%, 300%, and 400%, extending the range beyond the current maximum of 150%.
This commit contains the file `ParamDialog.cpp` modified to include these new size options.
=> adding 200%, 300% and 400% scaling options

Dexed.jucer, Source/CMakeLists.txt, Source/DXComponents.cpp, Source/DXComponents.h, Source/GlobalEditor.cpp, Source/GlobalEditor.h, Source/OperatorEditor.cpp, Source/OperatorEditor.h, Source/PluginEditor.cpp, Source/PluginProcessor.cpp, Source/PluginProcessor.h, Source/VUMeter.cpp, Source/VUMeter.h
Dear Pascal,
Please apply my current pull request. It implements faster dB-based solid-color VU meters for FM-operators and a tricolor stripe for the VU meter of the main output. 
In addition, further improvements have been introduced:
- during initialization, 47 solid color and 47 tricolor but single LED stripe images are created and stored in persitent arrays. 
The 0th element of this array shows all LEDs in dark color, the 1st element shows the leftmost LED in bright color, the 2nd element shows the two leftmost LEDs in bright color, and so on, until the last element, which contains all LEDs in bright.
- in the ``VuMeter::paint()`` method, there were previously two calls to the ``drawImage()`` method: the first one redrew the entire LED stripe in dark, and the second one redrew the …
=> implement faster dB-based VUMeters and a tricolor main VUMeter

Source/AlgoDisplay.cpp
Dear Pascal,
apply my current Pull Request to correct two graphs of Algorithm No. 15 and No. 14, please.
Currently, the operators' graph for Algorithm No. 15 looks like this:
The view is a bit misleading, as it suggests that the 5th and 6th operators modulate the both the 2nd and 4th operators simultaneously, but originally the 5th and 6th operators only modulate the 4th operator, not the 2nd one. Therefore, I slightly modified the image of the Algorithm No. 15 to the following:
Furthermore, the image of the Algorithm No. 14 currently looks like it below: 
However, if we compare this with the new graph of the Algorithm No. 15, the view might be confusing a bit, because there is only one essential difference between the two algorithms: namely, in the Algorithm No. 15, the 2nd operator has …
=> corrections of graphs for Algorithms 15 and 14

Source/AlgoDisplay.cpp, Source/CartManager.cpp, Source/CartManager.h, Source/PluginEditor.cpp, Source/PluginEditor.h, Source/PluginProcessor.cpp
The Cartridge Manager needed a haircut. If you click on the cartridge name on the right bottom it will open the OS file browser for this cartridge.
Comments are welcomed. 
Dev builds are available here : https://github.com/asb2m10/dexed/actions/runs/10032291816
This should close #379 and (already closed duplicate #374)
=> 379 Cartridge Manager refractor (see original cartridge name)

Source/GlobalEditor.cpp, Source/GlobalEditor.h, Source/PluginProcessor.cpp, Source/SysexComm.cpp, Source/SysexComm.h
Dear Pascal,
Now I am sending the one of the parts after splitting the [simplified AlignedBuf, corrected dexedTheme, code purification related to MidiMonitor #434](https://github.com/asb2m10/dexed/pull/434) in this PR; it contains only the corrections related to ``MidiMonitor`` class.
Unfortunately, another issue has arisen regarding DexedTheme (the build-macos step failed), so there is still work to be done there.
Furthermore, I have not yet found a good and general solution for ``AlignedBuf`` that would extend to older C++ compilers as well.
So for now, I’m just sending only this single PRs, (hoping that it can pass without further new tricky problems.)
Thank you for your patience!
=> code cleanup for MidiMonitor
